# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Weekly pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0"

{% raw -%}
jobs:
  auto-update-pre-commit:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-update-pre-commit.yml@1.3.0
    secrets:
      APP_ID: ${{ secrets.AUTO_PR_BOT_APP_ID }}
      PRIVATE_KEY: ${{ secrets.AUTO_PR_BOT_PRIVATE_KEY }}
{%- endraw %}

