# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Static Exemplar Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-exemplar-test:
    runs-on: ubuntu-latest
    container: ghcr.io/bemanproject/infra-containers-gcc:latest
    name: "Static exemplar smoke test"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test static exemplar
        run: |
          cd cookiecutter
          source ./check_cookiecutter.sh
          cookiecutter_venv_path=$(mktemp --directory --dry-run)
          setup_venv "$cookiecutter_venv_path"
          stamp "$PWD" "./static_exemplar" "static"
          cd static_exemplar/exemplar
          cmake -B build -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=./infra/cmake/use-fetch-content.cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_INSTALL_PREFIX=$PWD/dist
          cmake --build build
          ctest --test-dir build
          cmake --install build
